name: Deploy W5 - Weather

on:
  push:
    paths:
      - 'week5/2-weather/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week5/2-weather
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
